public class ValitiveQueryParams {

        public static final String HAPPENED_ON_OR_AFTER = 'happenedOnOrAfter';
        public static final String HAPPENED_BEFORE = 'happenedBefore';
        public static final String DETECTED_ON_OR_AFTER = 'detectedOnOrAfter';
        public static final String DETECTED_BEFORE = 'detectedBefore';
        public static final String EVENT_TYPES = 'eventTypes';
        public static final String SUBJECT_IDS = 'subjectIds';
        public static final String LEGAL_IDS = 'legalIds';
        public static final String PARTY_IDS = 'partyIds';
        public static final String ITERATOR = 'iterator';
        public static final String WITH_TOTAL = 'withTotal';
        public static final String SORT_BY = 'sortBy';
}