public class ValitiveQueryParams {

    public class EventQueryParams {
        public final static String HAPPENED_ON_OR_AFTER = 'happenedOnOrAfter';
        public final static String HAPPENED_BEFORE = 'happenedBefore';
        public final static String DETECTED_ON_OR_AFTER = 'detectedOnOrAfter';
        public final static String DETECTED_BEFORE = 'detectedBefore';
        public final static String EVENT_TYPES = 'eventTypes';
        public final static String SUBJECT_IDS = 'subjectIds';
        public final static String LEGAL_IDS = 'legalIds';
        public final static String PARTY_IDS = 'partyIds';
        public final static String ITERATOR = 'iterator';
        public final static String WITH_TOTAL = 'withTotal';
        public final static String SORT_BY = 'sortBy';
    }
}